name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: lab-20/live/dev/aks
        run: terraform init

      - name: Terraform Plan
        working-directory: lab-20/live/dev/aks
        run: terraform plan


  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: lab-20/live/dev/aks
        run: terraform init

      - name: Terraform Apply
        working-directory: lab-20/live/dev/aks
        run: terraform apply -auto-approve